[package]
name = "s3cli"
version = "0.0.0"
edition = "2024"
rust-version = "1.88"
publish = false

[dependencies]
shiguredo_s3 = { path = "../..", default-features = false, features = ["aws-lc-rs"] }
shiguredo_http11 = "2026.1.0"
rustls = { version = "0.23", default-features = false, features = [
    "std",
    "tls12",
    "aws_lc_rs",
] }
tokio = { version = "1", features = ["net", "io-util", "io-std", "rt-multi-thread", "sync", "fs"] }
tokio-rustls = { version = "0.26", default-features = false }
rustls-platform-verifier = "0.6"
noargs = "0.3"
